#!/bin/bash

trap 'exit $?' ERR

pushd () {
  command pushd "$@" > /dev/null
}

popd () {
  command popd "$@" > /dev/null
}

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

mkdir /var/log/werckit

echo 'export PS1="\u@container: "' >> /root/.bashrc
echo "export PATH=$DIR:\$PATH" >> /root/.bashrc
echo 'log' >> /root/.bashrc

export PATH="$DIR:$PATH"

step "checking connectivity"
export OFFLINE=true
export ONLINE=false
trap '' ERR
wget -q --tries=10 --timeout=20 --spider http://google.com
wget_res=$?
trap 'exit $?' ERR
if [[ $wget_res -eq 0 ]]
then
  export OFFLINE=false
  export ONLINE=true
  echo -e "connectivity: \033[1;32mONLINE\033[0m"
else
  echo -e "connectivity: \033[1;31mOFFLINE\033[0m"
fi

pushd ../
set -o allexport

step "check environment"
if [[ -f ENVIRONMENT_LOCAL.template && "$(cat ENVIRONMENT_LOCAL.template | xargs)" != "" && ! -f ENVIRONMENT_LOCAL ]]
then
  error "No ENVIRONMENT_LOCAL present, please create one based on ENVIRONMENT_LOCAL.template" && exit 1
fi

step "setup environment"
[[ -f ENVIRONMENT ]] && source ENVIRONMENT
[[ -f ENVIRONMENT_LOCAL ]] && source ENVIRONMENT_LOCAL

set +o allexport
popd

source "$DIR/../pipeline-$1"
