#!/bin/bash

pushd () {
  command pushd "$@" > /dev/null
}

popd () {
  command popd "$@" > /dev/null
}

mkdir /var/log/wercker

cp /app/.wercker/step /usr/bin/step
cp /app/.wercker/watch /usr/bin/watch
cp /app/.wercker/log /usr/bin/log
chmod +x /usr/bin/step
chmod +x /usr/bin/watch
chmod +x /usr/bin/log

echo 'export PS1="\u@container: "' > /root/.bashrc
echo 'log' > /root/.bashrc

step "checking connectivity"
export OFFLINE=true
export ONLINE=false
wget -q --tries=10 --timeout=20 --spider http://google.com
if [[ $? -eq 0 ]]
then
  export OFFLINE=false
  export ONLINE=true
  echo -e "connectivity: \033[1;32mONLINE\033[0m"
else
  echo -e "connectivity: \033[1;31mOFFLINE\033[0m"
fi

pushd ../
set -o allexport

step "check environment"
if [[ "$(cat ENVIRONMENT_LOCAL.template | xargs)" != "" && ! -f ENVIRONMENT_LOCAL ]]
then
  echo -e "\033[1;31mError:\033[0m No ENVIRONMENT_LOCAL present, please create one based on ENVIRONMENT_LOCAL.template" && exit 1
fi

step "setup environment"
[[ -f ENVIRONMENT ]] && source ENVIRONMENT
[[ -f ENVIRONMENT_LOCAL ]] && source ENVIRONMENT_LOCAL

set +o allexport
popd

"/app/pipeline-$1"
