#!/bin/bash

containers_running="$(docker-compose ps -q)"
[ ! -z "$containers_running" ] && echo "Removing running containers" && docker stop $containers_running

docker-compose up --remove-orphans -d
docker-compose run --service-ports main /app/pipeline dev

docker-compose stop
docker-compose rm -f
